# Generated by Django 3.1.7 on 2021-03-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=20)),
                ('Feedback', models.TextField(blank=True, null=True)),
                ('Session', models.TextField(blank=True, null=True)),
                ('Rating', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
        ),
    ]
